root = "."
tmp_dir = "tmp"
[build]
  bin = "tmp/main"
  cmd = "go build -o tmp/main ."
  delay = 2000
  exclude_dir = ["tmp", "vendor"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_ext = ["go.mod", "go.sum"]
  exclude_regex = ["_test.go"]

[log]
  level = "info"
  color = "true"
  time = "true"

[main]
  cmd = "tmp/main"
  watch_dir = "."
  exclude_dir = ["tmp", "vendor"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_ext = ["go.mod", "go.sum"]
  exclude_regex = ["_test.go"]
  delay = 2000

[formatter]
  binary_nextline = "true"
  formatters = [
    { binary = "goimports", args = "-w" }
  ]